SELECT 
id AS CoreStoreId,
country_id AS CountryId,
telegram_group_id AS TelegramGroupId,
blurring_id aS BlurringId,
currency_id AS CurrencyId,
language_id AS LanguageId,
timezone_id AS TimezoneId,
store_manager_id AS StoreManagerId,
alert_channel_id AS AlertChannelId,
deep_model_id AS DeepModelId,
buttons_type_id AS ButtonsTypeId,
name,
location,
server_ip AS ServerIp,
body_theft AS IsBodyTheft,
burst_shot AS BurstShot,
in_furious AS InFurious,
simulation,
consumption,
no_stroller AS NoStroller,
send_to_app AS SendToApp,
deblistering,
show_latency AS ShowLatency,
time_updated AS TimeUpdated,
allow_dataset AS AllowDataset,
no_suspicious AS NoSuspicious, 
good_bandwidth AS GoodBandWith,
suspicious_bag AS SuspiciousBag,
watcher_alerts AS WatcherAlerts,
anaveo_vt_alert AS AnaveoVtAlert,
local_inference AS LocalInference,
show_alert_time AS ShowAlertTime,
show_alert_type AS ShowAlertType,
show_cam_number AS ShowCamNumber,
alert_expiration AS AlertExpiration,
other_suspicious AS OtherSuspicious,
store_normal_bag AS StoreNormalbag
FROM {{source('veesion_manager', 'core_store')}}
QUALIFY ROW_NUMBER() OVER(PARTITION BY Id ORDER BY _airbyte_extracted_at ASC) = 1