SELECT 
Id AS UserId,
AccountId,
ContactId,
ManagerId,
ProfileId,
UserRoleId,
TopManagerId__c AS TopManagerId,
Username,
CompanyName,
FirstName,
Name,
LastName,
Suffix,
Title,
Alias,
Email,
Phone,
MobilePhone,
State,
Street,
City,
Department,
Address,
Country,
StateCode,
PostalCode,
IsActive,
Latitude,
Longitude,
UserType,
CountryCode,
Languages__c AS Languages,
TimeZoneSidKey,
ActivityTimezones__c AS ActivityTimezones,
CurrencyIsoCode,
FullPhotoUrl,
SmallPhotoUrl,
BannerPhotoUrl,
MediumPhotoUrl,
SmallBannerPhotoUrl,
CreatedDate,
LastLoginDate,
LastViewedDate,
LastModifiedDate,
LastReferencedDate,
IsProfilePhotoActive,
LastPasswordChangeDate,
EmailPreferencesAutoBcc,
ReceivesAdminInfoEmails

FROM {{source('salesforce', 'User')}}
QUALIFY ROW_NUMBER() OVER(PARTITION BY Id ORDER BY _airbyte_extracted_at ASC) = 1