name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up DBT environment
        uses: docker://fishtownanalytics/dbt:latest  # Utiliser l'image Docker DBT

      - name: Run dbt debug
        run: |
          dbt debug

      - name: Run dbt test
        run: |
          dbt test
